# General settings
lsi: false
safe: true
incremental: false

# Specify the source directory for Jekyll
source: docs

# Syntax highlighting and markdown settings
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Theme and plugin settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme